- name: OpenVPN setup
  hosts: localhost
  connection: local
  environment:
    EASYRSA_PKI: /pki
    EASYRSA_BATCH: yes
  tasks:
  - name: Install latest version of EasyRSA library
    yum:
      name: easy-rsa
      state: latest

  - name: Initialize PKI
    command: /usr/share/easy-rsa/3/easyrsa init-pki
    args:
      creates: /pki/private

  - name: Generate DH parameters
    command: /usr/share/easy-rsa/3/easyrsa gen-dh
    args:
      creates: /pki/dh.pem

  - name: Generate CA certificate and key
    command: /usr/share/easy-rsa/3/easyrsa --req-cn="OpenVPN CA" build-ca nopass
    args:
      creates: /pki/ca.crt

  - name: Generate server certificate and key
    command: /usr/share/easy-rsa/3/easyrsa build-server-full {{ server_host }} nopass
    args:
      creates: /pki/issued/{{ server_host }}.crt

  - name: Generate client certificate and key
    command: /usr/share/easy-rsa/3/easyrsa build-client-full {{client_name}} nopass
    args:
      creates: /pki/issued/{{ client_name }}.crt

  - name: Install latest version of OpenVPN server
    yum:
      name: openvpn
      state: latest

  - name: Render OpenVPN server config
    template:
      src: /ansible/server.conf.j2
      dest: /etc/openvpn/server.conf

  - name: Render OpenVPN client config
    template:
      src: /ansible/client.conf.j2
      dest: /etc/openvpn/client.conf
