- name: OpenVPN setup
  hosts: localhost
  connection: local
  environment:
    EASYRSA_PKI: /pki
    EASYRSA_BATCH: yes
  tasks:
  - name: Install latest version of EasyRSA library
    yum:
      name: easy-rsa
      state: latest
      
  - name: Initialize PKI
    command: /usr/share/easy-rsa/3/easyrsa init-pki
    
  - name: Generate DH parameters
    command: /usr/share/easy-rsa/3/easyrsa gen-dh
    args:
      creates: /pki/dh.pem

  - name: Generate CA certificate and key
    command: /usr/share/easy-rsa/3/easyrsa --req-cn="OpenVPN CA" build-ca nopass
    args:
      creates: /pki/ca.crt

  - name: Generate server certificate and key
    command: /usr/share/easy-rsa/3/easyrsa build-server-full {{ server }} nopass
    args:
      creates: /pki/issued/{{ server }}.crt

  - name: Generate client certificate and key
    command: /usr/share/easy-rsa/3/easyrsa build-client-full client nopass
    args:
      creates: /pki/issued/client.key
      
  - name: Install latest version of OpenVPN server
    yum:
      name: openvpn
      state: latest

  - name: Render OpenVPN server config
    template:
      src: /ansible/server.conf.j2
      dest: /etc/openvpn/server.conf

  - name: Render OpenVPN client config
    template:
      src: /ansible/client.conf.j2
      dest: /etc/openvpn/client.conf

  - name: Render start script
    template:
      src: /ansible/start.j2
      dest: /start

  - name: Bless start script
    file:
      dest: /start
      mode: a+x
